# Generated by Django 3.2.3 on 2021-06-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroup', '0002_alter_membership_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
