# Generated by Django 3.2.5 on 2021-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workgroup', '0003_alter_workgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='workgroup_type',
            field=models.CharField(choices=[('ASP', 'aspect'), ('MNT', 'maintenance'), ('ADM', 'admin')], max_length=3, verbose_name='type'),
        ),
    ]
