---
default:
  AUTH_PASSWORD_VALIDATORS:
  - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
  - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
  - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
  - NAME: django.contrib.auth.password_validation.NumericPasswordValidator
  AUTH_USER_MODEL: user.User
  BASE_DIR: /home/czar/Dev/schooladmin
  CRISPY_TEMPLATE_PACK: bootstrap4
  DEFAULT_AUTO_FIELD: django.db.models.AutoField
  DEFAULT_SETTINGS_PATHS:
  - settings.yaml
  - .secrets.yaml
  EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
  INSTALLED_APPS:
  - user.apps.UserConfig
  - base.apps.BaseConfig
  - center.apps.CenterConfig
  - person.apps.PersonConfig
  - workgroup.apps.WorkgroupConfig
  - event.apps.EventConfig
  - treasury.apps.TreasuryConfig
  - django.contrib.admin
  - django.contrib.auth
  - django.contrib.contenttypes
  - django.contrib.sessions
  - django.contrib.messages
  - django.contrib.staticfiles
  - crispy_forms
  LANGUAGE_CODE: pt-BR
  LOAD_DOTENV: true
  LOGIN_REDIRECT_URL: /user/profile/detail/
  LOGIN_URL: login
  MIDDLEWARE:
  - django.middleware.security.SecurityMiddleware
  - django.contrib.sessions.middleware.SessionMiddleware
  - django.middleware.common.CommonMiddleware
  - django.middleware.csrf.CsrfViewMiddleware
  - django.contrib.auth.middleware.AuthenticationMiddleware
  - django.contrib.messages.middleware.MessageMiddleware
  - django.middleware.clickjacking.XFrameOptionsMiddleware
  ROOT_URLCONF: schooladmin.urls
  STATIC_URL: /static/
  MEDIA_ROOT: /home/czar/Dev/schooladmin/media
  MEDIA_URL: /media/
  TEMPLATES:
  - APP_DIRS: true
    BACKEND: django.template.backends.django.DjangoTemplates
    DIRS:
    - /home/czar/Dev/schooladmin/templates
    OPTIONS:
      context_processors:
      - django.template.context_processors.debug
      - django.template.context_processors.request
      - django.contrib.auth.context_processors.auth
      - django.contrib.messages.context_processors.messages
      - schooladmin.context_processors.export_vars
  TIME_ZONE: America/Sao_Paulo
  USE_I18N: true
  USE_L10N: true
  USE_TZ: true
  WSGI_APPLICATION: schooladmin.wsgi.application
  APP_NAME: rc@dmin

development:
  DEBUG: true
  ALLOWED_HOSTS:
  - 'localhost'
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: /home/czar/Dev/schooladmin/schooladmin_db.sqlite3
