# Generated by Django 3.2.3 on 2021-05-19 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CTT", "contact"), ("MET", "meeting")],
                        default="CTT",
                        max_length=3,
                    ),
                ),
                ("theme", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="center.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "lecture",
                "verbose_name_plural": "lectures",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Seeker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("name_sa", models.CharField(editable=False, max_length=80)),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default_profile.jpg", upload_to="profile_pics"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=50)),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="state"
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=50)),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="phone"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("observations", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="center.center",
                    ),
                ),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="made_by_seeker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "seeker",
                "verbose_name_plural": "seekers",
            },
        ),
        migrations.CreateModel(
            name="Listener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ranking", models.IntegerField(default=0)),
                (
                    "observations",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="publicwork.lecture",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="publicwork.seeker",
                    ),
                ),
            ],
            options={
                "verbose_name": "listener",
                "verbose_name_plural": "listeners",
            },
        ),
        migrations.AddField(
            model_name="lecture",
            name="listeners",
            field=models.ManyToManyField(
                blank=True,
                through="publicwork.Listener",
                to="publicwork.Seeker",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="made_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_lecture",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Historic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurrence",
                    models.CharField(
                        choices=[
                            ("NEW", "new"),
                            ("REG", "regular"),
                            ("INT", "interview"),
                            ("SVC", "service"),
                            ("CNF", "conference"),
                            ("OTH", "other"),
                        ],
                        default="NEW",
                        max_length=3,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="made_by_historic_of_seeker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="publicwork.seeker",
                    ),
                ),
            ],
            options={
                "verbose_name": "historic",
                "verbose_name_plural": "historics",
            },
        ),
    ]
