# Generated by Django 3.2.3 on 2021-06-11 14:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicwork', '0003_alter_lecture_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Historic',
            new_name='Historic_of_seeker',
        ),
    ]
