# Generated by Django 3.2.3 on 2021-06-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicwork', '0003_alter_lecture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker',
            name='country',
            field=models.CharField(choices=[('BR', 'Brasil')], default='BR', max_length=2),
        ),
    ]
