# Generated by Django 3.2.3 on 2021-06-24 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_historic_description'),
        ('center', '0003_auto_20210617_0930'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicwork', '0005_auto_20210617_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicworkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='center.center')),
                ('made_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='made_by_publicwork_group', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to='publicwork.Seeker')),
                ('mentors', models.ManyToManyField(to='person.Person')),
            ],
            options={
                'verbose_name': 'publicwork group',
                'verbose_name_plural': 'publicwork groups',
            },
        ),
    ]
