# Generated by Django 3.2.3 on 2021-06-29 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicwork', '0007_auto_20210624_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricOfSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence', models.CharField(choices=[('MBR', 'member'), ('RCP', 'reception'), ('INS', 'installing'), ('RST', 'restriction')], default='MBR', max_length=3)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='made_by_historic_of_seeker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historic',
                'verbose_name_plural': 'historics',
            },
        ),
        migrations.AlterField(
            model_name='seeker',
            name='status',
            field=models.CharField(blank=True, choices=[('MBR', 'member'), ('RCP', 'reception'), ('INS', 'installing'), ('RST', 'restriction')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Historic_of_seeker',
        ),
        migrations.AddField(
            model_name='historicofseeker',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='publicwork.seeker'),
        ),
    ]
