# Generated by Django 3.2.5 on 2021-07-05 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('publicwork', '0008_auto_20210629_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRegOfSeeker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1)),
                ('image', models.ImageField(blank=True, default='default_profile.jpg', upload_to='profile_pics')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2, verbose_name='state')),
                ('country', models.CharField(choices=[('BR', 'Brasil')], default='BR', max_length=2)),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('observations', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.IntegerField(default=3980, editable='False')),
            ],
            options={
                'verbose_name': 'temporary registration of seeker',
                'verbose_name_plural': 'temporary registration of seekers',
            },
        ),
    ]
