# Generated by Django 3.2.5 on 2021-07-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publicwork", "0009_tempregofseeker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tempregofseeker",
            name="observations",
        ),
        migrations.AlterField(
            model_name="tempregofseeker",
            name="code",
            field=models.IntegerField(),
        ),
    ]
