# Generated by Django 3.2.5 on 2021-07-08 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('publicwork', '0011_auto_20210707_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempregofseeker',
            name='solicited_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 9, 37, 43, 992538, tzinfo=utc)),
        ),
    ]
