# Generated by Django 3.2.5 on 2021-07-08 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicwork', '0012_alter_tempregofseeker_solicited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempregofseeker',
            name='solicited_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
