# Generated by Django 3.2.5 on 2021-07-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicwork', '0014_auto_20210710_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicofseeker',
            name='occurrence',
            field=models.CharField(choices=[('NEW', 'new'), ('MBR', 'member'), ('RCP', 'reception'), ('INS', 'installing'), ('RST', 'restriction')], default='MBR', max_length=3),
        ),
        migrations.AlterField(
            model_name='seeker',
            name='status',
            field=models.CharField(blank=True, choices=[('NEW', 'new'), ('MBR', 'member'), ('RCP', 'reception'), ('INS', 'installing'), ('RST', 'restriction')], max_length=3),
        ),
    ]
