# Generated by Django 3.1.7 on 2021-02-23 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
        ('person', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activity_type', models.CharField(choices=[('SRV', 'service'), ('CNF', 'conference'), ('CTT', 'contact'), ('OTH', 'other')], default='SRV', max_length=3, verbose_name='type')),
                ('multi_date', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='event_qr_codes')),
                ('date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPN', 'open'), ('CLS', 'close')], default='OPN', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.activity')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='center.center')),
                ('frequencies', models.ManyToManyField(blank=True, to='person.Person')),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['date'],
            },
        ),
    ]
