# Generated by Django 3.2.3 on 2021-05-31 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ranking", models.IntegerField(default=0)),
                (
                    "observations",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="event.event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="person.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "frequency",
                "verbose_name_plural": "frequencies",
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="frequencies",
        ),
        migrations.AddField(
            model_name="event",
            name="frequencies",
            field=models.ManyToManyField(
                blank=True, through="event.Frequency", to="person.Person"
            ),
        ),
    ]
