# Generated by Django 3.2.3 on 2021-06-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210531_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='aspect',
            field=models.CharField(choices=[('--', '--'), ('PW', 'Public Work'), ('YW', 'Youth Work'), ('A1', '1st. Aspect'), ('A2', '2nd. Aspect'), ('A3', '3rd. Aspect'), ('A4', '4th. Aspect'), ('GR', 'Grail'), ('A5', '5th. Aspect'), ('A6', '6th. Aspect')], default='--', max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('SRV', 'service'), ('CNF', 'conference'), ('MET', 'meeting'), ('CTT', 'contact'), ('OTH', 'other')], default='SRV', max_length=3, verbose_name='type'),
        ),
    ]
