# Generated by Django 3.2.3 on 2021-05-19 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("center", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reg", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=80)),
                ("name_sa", models.CharField(editable=False, max_length=80)),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="id card"
                    ),
                ),
                ("birth", models.DateField(blank=True, null=True)),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("PUP", "pupil"),
                            ("WEB", "web pupil"),
                            ("GST", "gest"),
                        ],
                        default="PUP",
                        max_length=3,
                        verbose_name="type",
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("--", "--"),
                            ("PW", "Public Work"),
                            ("YW", "Youth Work"),
                            ("A1", "1st. Aspect"),
                            ("A2", "2nd. Aspect"),
                            ("A3", "3rd. Aspect"),
                            ("A4", "4th. Aspect"),
                            ("GR", "Grail"),
                            ("A5", "5th. Aspect"),
                            ("A6", "6th. Aspect"),
                        ],
                        default="--",
                        max_length=2,
                    ),
                ),
                ("aspect_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("---", "---"),
                            ("ACT", "active"),
                            ("LIC", "licensed"),
                            ("DEA", "dead"),
                            ("DIS", "disconnected"),
                            ("REM", "removed"),
                        ],
                        default="---",
                        max_length=3,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="center.center",
                    ),
                ),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="made_by_person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "persons",
            },
        ),
        migrations.CreateModel(
            name="Historic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurrence",
                    models.CharField(
                        choices=[
                            ("TRF", "transfered"),
                            ("RGS", "regressed"),
                            ("OTH", "other"),
                            ("PRP", "preparatório"),
                            ("PRB", "probatório"),
                            ("PRF", "professo"),
                            ("--", "--"),
                            ("PW", "Public Work"),
                            ("YW", "Youth Work"),
                            ("A1", "1st. Aspect"),
                            ("A2", "2nd. Aspect"),
                            ("A3", "3rd. Aspect"),
                            ("A4", "4th. Aspect"),
                            ("GR", "Grail"),
                            ("A5", "5th. Aspect"),
                            ("A6", "6th. Aspect"),
                            ("---", "---"),
                            ("ACT", "active"),
                            ("LIC", "licensed"),
                            ("DEA", "dead"),
                            ("DIS", "disconnected"),
                            ("REM", "removed"),
                        ],
                        default="ACT",
                        max_length=3,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="made_by_historic",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="person.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "historic",
                "verbose_name_plural": "historics",
            },
        ),
    ]
