# Generated by Django 3.2.3 on 2021-06-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_alter_center_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='center',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='backup phone'),
        ),
    ]
