# Generated by Django 3.2 on 2021-04-17 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import treasury.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankFlags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'bank and flag',
                'verbose_name_plural': 'banks and flags',
            },
        ),
        migrations.CreateModel(
            name='FormOfPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payform_type', models.CharField(choices=[('PIX', 'pix'), ('CSH', 'cash'), ('CHK', 'check'), ('PRE', 'pre check'), ('DBT', 'debit'), ('CDT', 'credit'), ('DPT', 'deposit'), ('TRF', 'transfer'), ('SLP', 'bank slip')], default='CSH', max_length=3)),
                ('ctrl_number', models.CharField(blank=True, max_length=36, null=True)),
                ('complement', models.CharField(blank=True, max_length=36, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('voucher_img', models.ImageField(blank=True, null=True, upload_to=treasury.models.voucher_img_filename)),
                ('bank_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasury.bankflags')),
            ],
            options={
                'verbose_name': 'form of payment',
                'verbose_name_plural': 'form of payments',
            },
        ),
        migrations.CreateModel(
            name='PayTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'pay types',
                'verbose_name_plural': 'pay types',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ref_month', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('obs', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.event')),
                ('paytype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasury.paytypes')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('CCL', 'canceled'), ('PND', 'pending'), ('CCD', 'concluded')], default='PND', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('self_payed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='center.center')),
                ('form_of_payments', models.ManyToManyField(to='treasury.FormOfPayment')),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='made_by_order', to=settings.AUTH_USER_MODEL)),
                ('payments', models.ManyToManyField(to='treasury.Payment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
