# Generated by Django 3.2.3 on 2021-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytypes',
            name='code',
        ),
        migrations.AddField(
            model_name='paytypes',
            name='pay_type',
            field=models.CharField(choices=[('MON', 'monthly'), ('EVE', 'by event'), ('CAM', 'campaign')], default='MON', max_length=3),
        ),
    ]
