# Generated by Django 3.2.3 on 2021-06-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_auto_20210606_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
