# Generated by Django 3.2.3 on 2021-06-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('BR', 'Brasil')], default='BR', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='backup phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sos_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='emergency phone'),
        ),
    ]
